# MegaLinter configuration — disable noisy checkers
DISABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - ACTION_ACTIONLINT
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - HTML_DJLINT
  - HTML_HTMLHINT
APPLY_FIXES: all
FORMATTERS_DISABLE_ERRORS: true
